[default]
APP_NAME = "projektownia-flask"
SECRET_KEY = 'the random string'
DEBUG = false
TITLE = "projektownia-api"
APP_ADMIN = ""
APP_MAIL_SENDER = ""
MAIL_SERVER = "smtp.googlemail.com"
MAIL_PORT = 587
MAIL_USE_TLS = false
MAIL_USE_SSL = false
MAIL_USERNAME = "None"
MAIL_PASSWORD = "None"
SQL_ALCHEMY_TRACK_NOTIFICATIONS = false


TEMPLATES_AUTO_RELOAD = true
DEBUG = true
DEBUG_TOOLBAR_ENABLED = true
DEBUG_TB_PROFILER_ENABLED = true
DEBUG_TB_PANELS = [
    "flask_debugtoolbar.panels.versions.VersionDebugPanel",
    "flask_debugtoolbar.panels.sqlalchemy.SQLAlchemyDebugPanel",
    "flask_debugtoolbar.panels.timer.TimerDebugPanel",
    "flask_debugtoolbar.panels.headers.HeaderDebugPanel",
    "flask_debugtoolbar.panels.request_vars.RequestVarsDebugPanel",
    "flask_debugtoolbar.panels.template.TemplateDebugPanel",
    "flask_debugtoolbar.panels.route_list.RouteListDebugPanel",
    "flask_debugtoolbar.panels.logger.LoggingPanel",
    "flask_debugtoolbar.panels.profiler.ProfilerDebugPanel",
    "flask_debugtoolbar.panels.config_vars.ConfigVarsDebugPanel"
]

DB_USERNAME = ''
DB_PASSWORD = ''
PG_DB_URI = 'postgresql://DB_USERNAME:DB_PASSWORD@nazwa_hosta/baza_danych'
SQLALCHEMY_DATABASE_URI = 'sqlite:////bezwzględna/ścieżka/do/bazy_danych'
SQLALCHEMY_BINDS = ''
SQLALCHEMY_TRACK_MODIFICATIONS = true



